### ISSUE TITLE
Error: expected value at line 1 column 1

### ISSUE THREAD

**Issue by jennypollack** [blacksmith-eth/blacksmith#369]
I am running an Anvil mainnet fork with Blacksmith but the contract verification seems to fail with the error "expected value at line 1 column 1"

On the interface it says "Import failed" .

Do I need to do the verification in order to get the contract into Blacksmith?

**Comment by unholypanda** [comment]
If you are trying to import a contract that has already been deployed to ethereum mainnet it will need to be verified on etherscan, yes. I can add a comment to the README to clarify this.

**Comment by unholypanda** [comment]
@jennypollack By the way, thank you for opening this issue! If you run into any additional problems don't hesitate to reach out or open additional issues.
